#!/bin/bash
# Generate `.cargo/config.toml` with [patch.crates-io] entries for every
# sibling `oxideav-*` repo checked out next to this one.
#
# Usage:
#   ./scripts/dev-patch.sh
#
# Expected layout:
#   parent/
#   ├── oxideav/            (this repo)
#   └── oxideav-<name>/     (any number of sibling repos)
#
# Siblings are discovered at runtime; no hard-coded list. Each sibling
# directory must contain a Cargo.toml with `name = "oxideav-<name>"` to
# be picked up. The generated `.cargo/config.toml` is gitignored, so
# every dev owns their own.

set -euo pipefail

cd "$(dirname "$0")/.."
repo_root="$(pwd)"

# Work relative to parent directory.
cd ..

config="$repo_root/.cargo/config.toml"
mkdir -p "$repo_root/.cargo"

{
    echo "# AUTO-GENERATED by scripts/dev-patch.sh — do not edit by hand."
    echo "# Run the script again after cloning / removing sibling repos."
    echo ""
    echo "[patch.crates-io]"
    # In-workspace published crates (oxideav-core / -codec / -container /
    # -pixfmt etc.) — sibling repos depend on these from crates.io, so we
    # must re-route them to the local path to avoid cargo picking up two
    # copies of the same crate (local + crates.io) and yielding
    # "mismatched types" errors.
    for dir in "$repo_root"/crates/oxideav-*/; do
        dir="${dir%/}"
        manifest="$dir/Cargo.toml"
        [ -f "$manifest" ] || continue
        name="$(grep -m1 '^name = ' "$manifest" | cut -d'"' -f2 || true)"
        basename="$(basename "$dir")"
        [ "$name" = "$basename" ] || continue
        echo "$basename = { path = \"crates/$basename\" }"
    done
    # Sibling oxideav-* repos checked out next to this one.
    for dir in oxideav-*/; do
        dir="${dir%/}"
        [ "$dir" = "oxideav" ] && continue
        manifest="$dir/Cargo.toml"
        [ -f "$manifest" ] || continue
        name="$(grep -m1 '^name = ' "$manifest" | cut -d'"' -f2 || true)"
        [ "$name" = "$dir" ] || continue
        echo "$dir = { path = \"../$dir\" }"
    done
} > "$config"

echo "wrote $config:"
cat "$config"
